//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-3354 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.06.10 at 12:38:13 PM IST 
//


package org.ipsuper.nexcom.datamodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ApprovalRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ApprovalRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="QoSParmeters" type="{http://ip-super.org/usecase/nexcom/}QoSParameters"/>
 *         &lt;element name="CustomerID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ttID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ApprovalRequest", propOrder = {
    "qoSParmeters",
    "customerID",
    "ttID"
})
public class ApprovalRequest {

    @XmlElement(name = "QoSParmeters", required = true)
    protected QoSParameters qoSParmeters;
    @XmlElement(name = "CustomerID", required = true)
    protected String customerID;
    @XmlElement(required = true)
    protected String ttID;

    /**
     * Gets the value of the qoSParmeters property.
     * 
     * @return
     *     possible object is
     *     {@link QoSParameters }
     *     
     */
    public QoSParameters getQoSParmeters() {
        return qoSParmeters;
    }

    /**
     * Sets the value of the qoSParmeters property.
     * 
     * @param value
     *     allowed object is
     *     {@link QoSParameters }
     *     
     */
    public void setQoSParmeters(QoSParameters value) {
        this.qoSParmeters = value;
    }

    /**
     * Gets the value of the customerID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCustomerID() {
        return customerID;
    }

    /**
     * Sets the value of the customerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCustomerID(String value) {
        this.customerID = value;
    }

    /**
     * Gets the value of the ttID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTtID() {
        return ttID;
    }

    /**
     * Sets the value of the ttID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTtID(String value) {
        this.ttID = value;
    }

}
