//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-3354 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.06.10 at 12:38:13 PM IST 
//


package org.ipsuper.nexcom.datamodel;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.ipsuper.nexcom.datamodel package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _QoSSupplierSEEResponse_QNAME = new QName("http://ip-super.org/usecase/nexcom/", "QoSSupplierSEEResponse");
    private final static QName _LoginRequest_QNAME = new QName("http://ip-super.org/usecase/nexcom/", "LoginRequest");
    private final static QName _QoSCEORequest_QNAME = new QName("http://ip-super.org/usecase/nexcom/", "QoSCEORequest");
    private final static QName _QoSUserConfirmationResponse_QNAME = new QName("http://ip-super.org/usecase/nexcom/", "QoSUserConfirmationResponse");
    private final static QName _QoSLegalResponse_QNAME = new QName("http://ip-super.org/usecase/nexcom/", "QoSLegalResponse");
    private final static QName _QoSSupplierSEERequest_QNAME = new QName("http://ip-super.org/usecase/nexcom/", "QoSSupplierSEERequest");
    private final static QName _QoSUserFinalContractConfirmationResponse_QNAME = new QName("http://ip-super.org/usecase/nexcom/", "QoSUserFinalContractConfirmationResponse");
    private final static QName _QoSUserConfirmationRequest_QNAME = new QName("http://ip-super.org/usecase/nexcom/", "QoSUserConfirmationRequest");
    private final static QName _LoginResponse_QNAME = new QName("http://ip-super.org/usecase/nexcom/", "LoginResponse");
    private final static QName _QosUserFinalContractConfirmationRequest_QNAME = new QName("http://ip-super.org/usecase/nexcom/", "QosUserFinalContractConfirmationRequest");
    private final static QName _QoSUserRequest_QNAME = new QName("http://ip-super.org/usecase/nexcom/", "QoSUserRequest");
    private final static QName _QoSLegalRequest_QNAME = new QName("http://ip-super.org/usecase/nexcom/", "QoSLegalRequest");
    private final static QName _QoSCEOResponse_QNAME = new QName("http://ip-super.org/usecase/nexcom/", "QoSCEOResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.ipsuper.nexcom.datamodel
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VoIPParameters }
     * 
     */
    public VoIPParameters createVoIPParameters() {
        return new VoIPParameters();
    }

    /**
     * Create an instance of {@link LoginResponse }
     * 
     */
    public LoginResponse createLoginResponse() {
        return new LoginResponse();
    }

    /**
     * Create an instance of {@link ApprovalRequest }
     * 
     */
    public ApprovalRequest createApprovalRequest() {
        return new ApprovalRequest();
    }

    /**
     * Create an instance of {@link LoginRequest }
     * 
     */
    public LoginRequest createLoginRequest() {
        return new LoginRequest();
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link QoSParameters }
     * 
     */
    public QoSParameters createQoSParameters() {
        return new QoSParameters();
    }

    /**
     * Create an instance of {@link QoSParametersMsg }
     * 
     */
    public QoSParametersMsg createQoSParametersMsg() {
        return new QoSParametersMsg();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QoSParametersMsg }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ip-super.org/usecase/nexcom/", name = "QoSSupplierSEEResponse")
    public JAXBElement<QoSParametersMsg> createQoSSupplierSEEResponse(QoSParametersMsg value) {
        return new JAXBElement<QoSParametersMsg>(_QoSSupplierSEEResponse_QNAME, QoSParametersMsg.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoginRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ip-super.org/usecase/nexcom/", name = "LoginRequest")
    public JAXBElement<LoginRequest> createLoginRequest(LoginRequest value) {
        return new JAXBElement<LoginRequest>(_LoginRequest_QNAME, LoginRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApprovalRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ip-super.org/usecase/nexcom/", name = "QoSCEORequest")
    public JAXBElement<ApprovalRequest> createQoSCEORequest(ApprovalRequest value) {
        return new JAXBElement<ApprovalRequest>(_QoSCEORequest_QNAME, ApprovalRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Document }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ip-super.org/usecase/nexcom/", name = "QoSUserConfirmationResponse")
    public JAXBElement<Document> createQoSUserConfirmationResponse(Document value) {
        return new JAXBElement<Document>(_QoSUserConfirmationResponse_QNAME, Document.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Document }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ip-super.org/usecase/nexcom/", name = "QoSLegalResponse")
    public JAXBElement<Document> createQoSLegalResponse(Document value) {
        return new JAXBElement<Document>(_QoSLegalResponse_QNAME, Document.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QoSParametersMsg }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ip-super.org/usecase/nexcom/", name = "QoSSupplierSEERequest")
    public JAXBElement<QoSParametersMsg> createQoSSupplierSEERequest(QoSParametersMsg value) {
        return new JAXBElement<QoSParametersMsg>(_QoSSupplierSEERequest_QNAME, QoSParametersMsg.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Document }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ip-super.org/usecase/nexcom/", name = "QoSUserFinalContractConfirmationResponse")
    public JAXBElement<Document> createQoSUserFinalContractConfirmationResponse(Document value) {
        return new JAXBElement<Document>(_QoSUserFinalContractConfirmationResponse_QNAME, Document.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApprovalRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ip-super.org/usecase/nexcom/", name = "QoSUserConfirmationRequest")
    public JAXBElement<ApprovalRequest> createQoSUserConfirmationRequest(ApprovalRequest value) {
        return new JAXBElement<ApprovalRequest>(_QoSUserConfirmationRequest_QNAME, ApprovalRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoginResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ip-super.org/usecase/nexcom/", name = "LoginResponse")
    public JAXBElement<LoginResponse> createLoginResponse(LoginResponse value) {
        return new JAXBElement<LoginResponse>(_LoginResponse_QNAME, LoginResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Document }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ip-super.org/usecase/nexcom/", name = "QosUserFinalContractConfirmationRequest")
    public JAXBElement<Document> createQosUserFinalContractConfirmationRequest(Document value) {
        return new JAXBElement<Document>(_QosUserFinalContractConfirmationRequest_QNAME, Document.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VoIPParameters }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ip-super.org/usecase/nexcom/", name = "QoSUserRequest")
    public JAXBElement<VoIPParameters> createQoSUserRequest(VoIPParameters value) {
        return new JAXBElement<VoIPParameters>(_QoSUserRequest_QNAME, VoIPParameters.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApprovalRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ip-super.org/usecase/nexcom/", name = "QoSLegalRequest")
    public JAXBElement<ApprovalRequest> createQoSLegalRequest(ApprovalRequest value) {
        return new JAXBElement<ApprovalRequest>(_QoSLegalRequest_QNAME, ApprovalRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Document }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ip-super.org/usecase/nexcom/", name = "QoSCEOResponse")
    public JAXBElement<Document> createQoSCEOResponse(Document value) {
        return new JAXBElement<Document>(_QoSCEOResponse_QNAME, Document.class, null, value);
    }

}
