//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-3354 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.06.10 at 12:38:13 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ip-super.org/usecase/nexcom/")
package org.ipsuper.nexcom.datamodel;
