//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-3354 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.06.10 at 12:38:13 PM IST 
//


package org.ipsuper.nexcom.datamodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QoSParameters complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="QoSParameters">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VolumeOfTraffic" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="CCR" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="ACD" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="PPD" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="CLI" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="price" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="VolumeOfTrafficWeight" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="CCRWeight" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="ACDWeight" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="PPDWeight" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="CLIWeight" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="PriceWeight" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "QoSParameters", propOrder = {
    "volumeOfTraffic",
    "ccr",
    "acd",
    "ppd",
    "cli",
    "price",
    "volumeOfTrafficWeight",
    "ccrWeight",
    "acdWeight",
    "ppdWeight",
    "cliWeight",
    "priceWeight"
})
public class QoSParameters {

    @XmlElement(name = "VolumeOfTraffic")
    protected float volumeOfTraffic;
    @XmlElement(name = "CCR")
    protected float ccr;
    @XmlElement(name = "ACD")
    protected float acd;
    @XmlElement(name = "PPD")
    protected float ppd;
    @XmlElement(name = "CLI")
    protected boolean cli;
    protected float price;
    @XmlElement(name = "VolumeOfTrafficWeight")
    protected float volumeOfTrafficWeight;
    @XmlElement(name = "CCRWeight")
    protected float ccrWeight;
    @XmlElement(name = "ACDWeight")
    protected float acdWeight;
    @XmlElement(name = "PPDWeight")
    protected float ppdWeight;
    @XmlElement(name = "CLIWeight")
    protected float cliWeight;
    @XmlElement(name = "PriceWeight")
    protected float priceWeight;

    /**
     * Gets the value of the volumeOfTraffic property.
     * 
     */
    public float getVolumeOfTraffic() {
        return volumeOfTraffic;
    }

    /**
     * Sets the value of the volumeOfTraffic property.
     * 
     */
    public void setVolumeOfTraffic(float value) {
        this.volumeOfTraffic = value;
    }

    /**
     * Gets the value of the ccr property.
     * 
     */
    public float getCCR() {
        return ccr;
    }

    /**
     * Sets the value of the ccr property.
     * 
     */
    public void setCCR(float value) {
        this.ccr = value;
    }

    /**
     * Gets the value of the acd property.
     * 
     */
    public float getACD() {
        return acd;
    }

    /**
     * Sets the value of the acd property.
     * 
     */
    public void setACD(float value) {
        this.acd = value;
    }

    /**
     * Gets the value of the ppd property.
     * 
     */
    public float getPPD() {
        return ppd;
    }

    /**
     * Sets the value of the ppd property.
     * 
     */
    public void setPPD(float value) {
        this.ppd = value;
    }

    /**
     * Gets the value of the cli property.
     * 
     */
    public boolean isCLI() {
        return cli;
    }

    /**
     * Sets the value of the cli property.
     * 
     */
    public void setCLI(boolean value) {
        this.cli = value;
    }

    /**
     * Gets the value of the price property.
     * 
     */
    public float getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     */
    public void setPrice(float value) {
        this.price = value;
    }

    /**
     * Gets the value of the volumeOfTrafficWeight property.
     * 
     */
    public float getVolumeOfTrafficWeight() {
        return volumeOfTrafficWeight;
    }

    /**
     * Sets the value of the volumeOfTrafficWeight property.
     * 
     */
    public void setVolumeOfTrafficWeight(float value) {
        this.volumeOfTrafficWeight = value;
    }

    /**
     * Gets the value of the ccrWeight property.
     * 
     */
    public float getCCRWeight() {
        return ccrWeight;
    }

    /**
     * Sets the value of the ccrWeight property.
     * 
     */
    public void setCCRWeight(float value) {
        this.ccrWeight = value;
    }

    /**
     * Gets the value of the acdWeight property.
     * 
     */
    public float getACDWeight() {
        return acdWeight;
    }

    /**
     * Sets the value of the acdWeight property.
     * 
     */
    public void setACDWeight(float value) {
        this.acdWeight = value;
    }

    /**
     * Gets the value of the ppdWeight property.
     * 
     */
    public float getPPDWeight() {
        return ppdWeight;
    }

    /**
     * Sets the value of the ppdWeight property.
     * 
     */
    public void setPPDWeight(float value) {
        this.ppdWeight = value;
    }

    /**
     * Gets the value of the cliWeight property.
     * 
     */
    public float getCLIWeight() {
        return cliWeight;
    }

    /**
     * Sets the value of the cliWeight property.
     * 
     */
    public void setCLIWeight(float value) {
        this.cliWeight = value;
    }

    /**
     * Gets the value of the priceWeight property.
     * 
     */
    public float getPriceWeight() {
        return priceWeight;
    }

    /**
     * Sets the value of the priceWeight property.
     * 
     */
    public void setPriceWeight(float value) {
        this.priceWeight = value;
    }

}
