//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-3354 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.06.10 at 12:38:13 PM IST 
//


package org.ipsuper.nexcom.datamodel;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;


/**
 * <p>Java class for VoIPPackage.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="VoIPPackage">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Gold Class"/>
 *     &lt;enumeration value="Silver Class"/>
 *     &lt;enumeration value="Best-effort Class"/>
 *     &lt;enumeration value="Non-standard"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum VoIPPackage {

    @XmlEnumValue("Best-effort Class")
    BEST_EFFORT_CLASS("Best-effort Class"),
    @XmlEnumValue("Gold Class")
    GOLD_CLASS("Gold Class"),
    @XmlEnumValue("Non-standard")
    NON_STANDARD("Non-standard"),
    @XmlEnumValue("Silver Class")
    SILVER_CLASS("Silver Class");
    private final String value;

    VoIPPackage(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static VoIPPackage fromValue(String v) {
        for (VoIPPackage c: VoIPPackage.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v.toString());
    }

}
